### ISSUE TITLE
 project to gradle| Jar

### ISSUE THREAD

**Issue by FuriosoJack** [jchambers/java-otp#6] opened 2018-10-26 16:31 UTC
Hi, friend, it would be great if this project was available to use as a dependency on Gradle to use it on Android or the JAR. I made a fork in this project to make that feature possible, but now I do not have much time. However, if you can add that functionality before I have more time available, it would be fabulous. Since I am short of time I will have to copy your classes and add them to my project .

**Comment by jchambers** [comment] 2018-10-26 17:51
I think this is a duplicate of #3. java-otp is already [available via Maven Central](https://search.maven.org/artifact/com.eatthepath/java-otp/0.1.0/jar).

**Closed by jchambers** 2018-10-26 17:51 UTC
